### ISSUE TITLE
Οικονομικά και ταμείο

### ISSUE THREAD

**Issue by Basilisvirus** [seed17/Issues-assembly#2]
Θα έχουμα ταμείο; Να ορίσουμε διαχειρηστή

**Comment by Basilisvirus** [comment]
ενας ταμειας διαχειρηζεται το ταμειο, οπου ο καθενας που μπορει να βαλει χρηματα, τα βαζει με υπογραφη και ημερομηνια.
Οποιος χρειαζεται χρηματα, επικοινωνει με τον ταμεια και του δινει τα χρηματα ο ταμειας. Ο ταμειας σημειωνει τα εξοδα και το ατομο. Έτσι, βλεπουμε και τα εξοδα που εχει το καθε πεδιο.

**Comment by Basilisvirus** [comment]
//λευτερης:
Για να δωθουν χρηματα, θα γινεται πληρη ενημερωση, και μετα απο συμβουλιο.

**Comment by GraniczkaKasper** [comment]
// Κάσπερ
Διαφωνώ στο κομμάτι του συμβουλίου.
Αν κάποιος χρειάζεται 50€, δεν έχει αξία να κάνουμε συμβούλιο.
Θα μαζευτούμε 5 - 6 άτομα, να συζητήσουμε ένα μια - δυο ώρες τι ακριβώς;
Ο χρόνος, που θα σπαταλήσουμε για το συμβούλιο, μας στοιχίζει πολύ περισσότερα.

**Comment by Basilisvirus** [comment]
Ξεκιναμε να εχουμε πορτοφολι, φυσικό πορτοφολι.
Ρωτησα στο space πως λεγεται η εφαρμογη που χρησιμοποιουν μεταξυ τους για να κρατανε λογαριασμους.

**Comment by Basilisvirus** [comment]
Issue μεταφέρθηκε στο gitlab
