### ISSUE TITLE
Ενημέρωση φοιτητών και συμμετέχοντες

### ISSUE THREAD

**Issue by Basilisvirus** [seed17/Issues-assembly#3]
Ενημερώθηκαν: 
Μιχάλης `mike.azov@gmail.com` as sqsmike
Βασίλης `basilisvirus@hotmail.com` as Basilisvirus
Κάσπερ `casper1551@gmail.com`
Λευτέρης `lefterisgyparis@gmail.com`
Κουντρέτ `countretspirou@gmail.com`

**Comment by GraniczkaKasper** [comment]
GDPR compliance

**Comment by Basilisvirus** [comment]
Εστειλα email στους παραπανω, για το θεμα.

**Comment by Basilisvirus** [comment]
Ανοιγω στο kanboard νεα ομαδα, βαζω ολα τα ατομα μεσα, διαγραφω τα στοιχεια του απο εδω.
Διαγραφω τελειως το issue.

**Comment by Basilisvirus** [comment]
issue μεταερθηκε στο gitlab
