### ISSUE TITLE
Καταστατικό

### ISSUE THREAD

**Issue by Basilisvirus** [seed17/Issues-assembly#5]
Ψηφοφορία έργου και/ή συγγραφή καταστατικού ομάδας.

Ιδεες εργων:

**Comment by GraniczkaKasper** [comment]
Να φέρουμε Templates στην συνεύρεση από κοντά

**Comment by GraniczkaKasper** [comment]
Θα συντάξω ένα πρώτο καταστατικό, και θα γίνει ενημέρωση για αυτό στις επόμενες συναντήσεις

**Comment by Basilisvirus** [comment]
1) Συγγραφω το καταστατικο.
2) μελεταμε διαδυκτιακο τροπο να επισημοποιηθεί η συμνμετοχή των μελών της ομάδας που αναγράφονται στο καταστατικό.

**Comment by Basilisvirus** [comment]
Να γραψω τα copyrights της ιδεας που μενουν.
Να γραψω πως κατανεμονται τα φραγκα. (Κατι παραπανω να παρει ο εχων την ιδεα)

**Comment by Basilisvirus** [comment]
issue μεταφέρθηκε στο gitlab
