### ISSUE TITLE
Ιδεες πανω στο transmitter

### ISSUE THREAD

**Issue by Basilisvirus** [seed17/Issues-assembly#6]
-Χρηση σε φωτοβολιδα.

-Baby monitoring/tracking [bluetooth] -Μιχαλης

// Κάσπερ
Πιθανές προσθήκες:
- Εξτρά laser - photoresistor
- Σύνδεση με ρούτερ για πρόσβαση στο διαδίκτυο ή σε απομακρυσμένες περιοχές
- Επικοινωνία σε περιοχές εκτός κάλυψης, με δορυφόρους ή σε δυσμενείς συνθήκες 
- Προσπέλαση συσκευών παρεμπόδισης - παρεμβολής σήματος (jammers)
- Επικοινωνία με Bluetooth (Bl) 5.1 για προσδιορισμό θέσης (π.χ. Σε μία επιχείρηση)
- Μέσω του Bl 5.1, δημιουργία Access Control 
Π.χ. ανίχνευση εγκεκριμένης παρουσίας στο χώρο σε συνδυασμό με κωδικό, και δικαιοδοσία ως προς τη θέση του στο χώρο. Στην αντίθετη, αποστολή σήματος μέσω του laser για την ειδοποίηση intruder.
- Escape Room
- Μέσω του Bl 5.1 μπορεί να γίνει προσδιορισμός στα γηροκομεία, νοσοκομεία, ή ψυχιατρεία της - θέσης των ασθενών
- Μέσω του Bl 5.1 έλεγχος βάση χρωματικής κάτοψης ενός χώρου
- Συνδυασμός Bluetooth + laser: απομακρυσμένη μεταφορά μεγάλου όγκου δεδομένων (π.χ. βίντεο) σε σημεία απουσίας ραδιοσυχνοτήτων
- Οπτικές ίνες
- Li-Fi (Λευτέρης)
- Ηχείο, και Μικρόφωνο

**Comment by GraniczkaKasper** [comment]
// Βασίλης
Έρευνα επάνω στα παρεμφερή πράγματα - πρότζεκτ, που υπάρχουν μέχρι στιγμής

**Comment by GraniczkaKasper** [comment]
https://www.polyxoros.com/project-morse/

**Comment by GraniczkaKasper** [comment]
https://www.quora.com/If-I-point-a-laser-at-a-window-of-the-ISS-will-the-astronauts-be-able-to-see-the-dot

**Με ένα watt laser :)**

**Comment by Basilisvirus** [comment]
Θα κάνουμε το έργο για Wireless Next Gen communication. Ξεκινάω μελέτη βιωσιμότητας
